#!/usr/bin/env python3
"""Generate the reference FIR crossover tables for sena-dsp.

All Sena crossovers share one design: a linear-phase low-pass designed with
scipy.signal.firwin (Kaiser beta 9.0, fs=48000, DC gain 1) with the
subtractive complement taken in the DSP code. The table is frozen source
(``do not edit``): regenerate only when a split point changes.

Designs:
  FIR_300   8001 taps, cutoff 300 Hz   (transition 0.2*fc = 60 Hz)
  FIR_600   4001 taps, cutoff 600 Hz   (transition 0.2*fc = 120 Hz)
  FIR_15600 2001 taps, cutoff 15480 Hz (transition 240 Hz, stopband at the
            Opus b19 edge 15600 Hz, >= ~95 dB there)

Usage:
  gen_fir_table.py <name>            print the `pub static` table
  gen_fir_table.py --verify          re-derive every table and diff in-memory

Requires numpy + scipy (the tables are generated by the reference design;
the Rust side never links them).
"""
import re
import sys

import numpy as np
from scipy.signal import firwin

FS = 48000.0
TABLES = {
    "FIR_300": (8001, 300.0),
    "FIR_600": (4001, 600.0),
    "FIR_15600": (2001, 15480.0),
}
RS_PATH = "crates/sena-dsp/src/fir_tables.rs"


def taps(name):
    n, fc = TABLES[name]
    return firwin(n, fc, window=("kaiser", 9.0), fs=FS)


def fmt(name, h):
    vals = [f"{v:.17e}" for v in h]
    lines = []
    for i in range(0, len(vals), 6):
        lines.append("    " + ", ".join(vals[i : i + 6]) + ",")
    body = "\n".join(lines)
    return f"pub static {name}: [f64; {len(h)}] = [\n{body}\n];\n"


def verify():
    src = open(RS_PATH).read()
    ok = True
    for name, (n, _fc) in TABLES.items():
        m = re.search(rf"pub static {name}: \[f64; (\d+)\] = \[(.*?)\];", src, re.S)
        if not m:
            print(f"{name}: MISSING from {RS_PATH}")
            ok = False
            continue
        want = np.array([float(x) for x in re.findall(r"[-\d.eE+]+", m.group(2))])
        got = taps(name)
        if len(want) != n:
            print(f"{name}: table has {len(want)} taps, design has {n}")
            ok = False
        elif not np.array_equal(want, got):
            d = np.abs(want - got).max()
            print(f"{name}: differs from reference design (max {d:.3e})")
            ok = False
        else:
            print(f"{name}: OK ({n} taps, bit-exact)")
    return ok


def main():
    if len(sys.argv) == 2 and sys.argv[1] == "--verify":
        sys.exit(0 if verify() else 1)
    if len(sys.argv) != 2 or sys.argv[1] not in TABLES:
        print(__doc__)
        sys.exit(2)
    sys.stdout.write(fmt(sys.argv[1], taps(sys.argv[1])))


if __name__ == "__main__":
    main()
